version: "3.3"
services:

  bcp-db:
    container_name: bcp-db
    image: postgres:12.5
    ports:
      - "5432"
    volumes:
      - ./storage/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: bcp
      POSTGRES_USER: bcp
      POSTGRES_DB: bcp

  bcp-web:
    container_name: bcp-web
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        build_env: development
    image: bcp-web
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - bcp-db
    environment:
      BCP_ENV: development
      DATABASE_URI: postgres://bcp:bcp@bcp-db/bcp
