#!/usr/bin/env python

import functools
import os
import sys

web_container = 'bcp-web'
db_container = 'bcp-db'
os.environ['DOCKER_BUILDKIT'] = '1'
os.environ['COMPOSE_DOCKER_CLI_BUILD'] = '1'


def command(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs)
    wrapper.is_manage_command = True
    return wrapper


def run(cmd):
    print(f' -> {cmd}')
    os.system(f'{cmd}')


def crun(cmd, container=web_container):
    run(f'docker exec -it {container} {cmd}')


@command
def manage(args):
    crun('django-admin {}'.format(' '.join(args)))


@command
def bash(args):
    crun('bash {}'.format(' '.join(args)))


@command
def start(args):
    os.system('docker-compose up -d')


@command
def rebuild(args):
    os.system('docker-compose stop')
    os.system('docker-compose rm -f')

    if '-b' in args:
        os.system('docker-compose build')

    start(args)


if __name__ == '__main__':
    argv = sys.argv[1:]
    cmd = 'manage'

    try:
        if globals()[argv[0]].is_manage_command:
            cmd = argv[0]
            argv = argv[1:]
    except (KeyError, IndexError):
        pass

    globals()[cmd](argv)
