#!/usr/bin/env python

import os
import time

from bcp import dockerman as dm

web_container = 'bcp-web'
db_container = 'bcp-db'
os.environ['DOCKER_BUILDKIT'] = '1'
os.environ['COMPOSE_DOCKER_CLI_BUILD'] = '1'
dm.default_container = web_container


@dm.command
def manage(args, extras):
    """Run Django admin commands on the web container."""
    dm.crun('django-admin {}'.format(' '.join(extras)))


@dm.command
def bash(args, extras):
    """Open a bash shell on the web container."""
    dm.crun('bash {}'.format(' '.join(extras)))


@dm.command
@dm.option(
    '-b', '--build',
    action='store_const',
    dest='build',
    const=True,
    default=False,
    help='Rebuild images',
)
def rebuild(args, extras):
    """Remove and rebuild containers."""
    dm.run('docker-compose stop')
    dm.run('docker-compose rm -f')

    if args.build:
        dm.run('docker-compose build')

    dm.run('docker-compose up -d')


@dm.command
def debug(args, extras):
    """Attach to web container for debugging."""
    dm.run(f'docker attach {web_container}')


@dm.command
@dm.option(
    '-i', '--import',
    dest='import_file',
    help='Import SQL file',
)
@dm.option(
    '-n', '--nomigrate',
    action='store_const',
    dest='nomigrate',
    const=True,
    default=False,
    help='Do not automatically run migrations',
)
def resetdb(args, extras):
    """Reset database data."""
    dm.run(f'docker-compose stop {db_container}')
    dm.run(f'docker-compose rm -f {db_container}')

    dm.run('sudo rm -rf storage/db')
    dm.run(f'docker-compose up -d {db_container}')
    print('Waiting for database to come up...')
    time.sleep(5)

    if args.import_file:
        dm.run(
            f'docker exec -i {db_container} psql -U bcp -d bcp < '
            f'{args.import_file}'
        )

    if not args.nomigrate:
        dm.crun('django-admin migrate')


if __name__ == '__main__':
    dm.run_commands()
