# Generated by Django 3.1.1 on 2020-09-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='A unique name for this chunk of content', max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
